id: e8545dab564940b1ac056dfcb882d6fa
title: Toh_164-The_Questions_of_Ratnacandra-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-059-007
  eft-text-version: 1.2.5 2020
